// <auto-generated />
using System;
using Lotofacil.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lotofacil.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814011353_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseContestContest", b =>
                {
                    b.Property<int>("BaseContestId")
                        .HasColumnType("int");

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.HasKey("BaseContestId", "ContestId");

                    b.HasIndex("ContestId");

                    b.ToTable("BaseContestContest", (string)null);
                });

            modelBuilder.Entity("Lotofacil.Domain.Entities.BaseContest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<int>("Hit11")
                        .HasColumnType("int")
                        .HasColumnName("Hit11");

                    b.Property<int>("Hit12")
                        .HasColumnType("int")
                        .HasColumnName("Hit12");

                    b.Property<int>("Hit13")
                        .HasColumnType("int")
                        .HasColumnName("Hit13");

                    b.Property<int>("Hit14")
                        .HasColumnType("int")
                        .HasColumnName("Hit14");

                    b.Property<int>("Hit15")
                        .HasColumnType("int")
                        .HasColumnName("Hit15");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<string>("Numbers")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("Numbers");

                    b.Property<string>("TopTenNumbers")
                        .HasMaxLength(29)
                        .HasColumnType("nvarchar(29)")
                        .HasColumnName("TopTenNumbers");

                    b.Property<int?>("TotalProcessed")
                        .HasColumnType("int")
                        .HasColumnName("TotalProcessed");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("Name");

                    b.ToTable("BaseContest", (string)null);
                });

            modelBuilder.Entity("Lotofacil.Domain.Entities.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<DateTime?>("LastProcessedMainJob")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastProcessedMainJob");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<string>("Numbers")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("Numbers");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("LastProcessedMainJob");

                    b.HasIndex("Name");

                    b.ToTable("Contest", (string)null);
                });

            modelBuilder.Entity("Lotofacil.Domain.Entities.ContestActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseContestName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BaseContestName");

                    b.Property<string>("BaseContestNumbers")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("BaseContestNumbers");

                    b.Property<int>("CountHits")
                        .HasColumnType("int")
                        .HasColumnName("CountHits");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateTime");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<string>("Numbers")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("Numbers");

                    b.HasKey("Id");

                    b.HasIndex("BaseContestName");

                    b.ToTable("ContestActivityLog", (string)null);
                });

            modelBuilder.Entity("BaseContestContest", b =>
                {
                    b.HasOne("Lotofacil.Domain.Entities.BaseContest", null)
                        .WithMany()
                        .HasForeignKey("BaseContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lotofacil.Domain.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
